#下面这些内容是为了让MyBatis映射
#指定Mybatis的Mapper文件
#mybatis.mapper-locations=classpath:mappers/*xml
#指定Mybatis的实体目录
#mybatis.type-aliases-package=com.bushlay.springbootmybatis.mybatis.entity
spring:
  datasource:
      url: jdbc:mysql://localhost:3306/springboot
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver

# mybatis
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml # mapper映射文件路径

#config-location: # 指定mybatis的核心配置文件